import LeftComponent from "@/Components/LeftComponent";
import Main from "@/Components/Main";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#EFEFEF]">
        <div className="flex">
          <LeftComponent />
          <Main />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
